# Default initial positions for Poppy_Humanoid's ros2_control fake system

initial_positions:
  abs_x: 0
  abs_y: 0
  abs_z: 0
  bust_x: 0
  bust_y: 0
  head_y: 0
  head_z: 0
  l_ankle_y: 0
  l_arm_z: 0
  l_elbow_y: 0
  l_hip_x: 0
  l_hip_y: 0
  l_hip_z: 0
  l_knee_y: 0
  l_shoulder_x: 0
  l_shoulder_y: 0
  r_ankle_y: 0
  r_arm_z: 0
  r_elbow_y: 0
  r_hip_x: 0
  r_hip_y: 0
  r_hip_z: 0
  r_knee_y: 0
  r_shoulder_x: 0
  r_shoulder_y: 0