# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  abs_x:
    has_velocity_limits: true
    max_velocity: 8.1999999999999993
    has_acceleration_limits: false
    max_acceleration: 0.0
  abs_y:
    has_velocity_limits: true
    max_velocity: 8.1999999999999993
    has_acceleration_limits: false
    max_acceleration: 0.0
  abs_z:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  bust_x:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  bust_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  head_y:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  head_z:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_ankle_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_arm_z:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_elbow_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_hip_x:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_hip_y:
    has_velocity_limits: true
    max_velocity: 8.1999999999999993
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_hip_z:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_knee_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_shoulder_x:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  l_shoulder_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_ankle_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_arm_z:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_elbow_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_hip_x:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_hip_y:
    has_velocity_limits: true
    max_velocity: 8.1999999999999993
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_hip_z:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_knee_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_shoulder_x:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  r_shoulder_y:
    has_velocity_limits: true
    max_velocity: 7.0
    has_acceleration_limits: false
    max_acceleration: 0.0
